<Project>
    <PropertyGroup>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <EnforceCodeStyleInBuild>false</EnforceCodeStyleInBuild>
        <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
        <GenerateDocumentationFile>false</GenerateDocumentationFile>
    </PropertyGroup>
</Project>