<Project Sdk="Godot.NET.Sdk/4.6.2">

    <PropertyGroup>
        <!-- Disable Central Package Management for Godot projects -->
        <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
        <TargetFramework>net9.0</TargetFramework>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
        <RootNamespace>LostInSpace</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>
</Project>
