name: Build project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./LostInSpace

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore LostInSpace.sln

      - name: Check formatting
        run: dotnet format LostInSpace.sln --verify-no-changes --verbosity diagnostic

      - name: Build project
        run: dotnet build LostInSpace.sln --configuration ExportRelease --no-restore

      - name: Run tests
        run: dotnet test LostInSpace.sln
